### ISSUE TITLE
Difficulty entering in a phone number

### ISSUE THREAD

**Issue by MurrayJack** [SimpleProgrammingAU/CovidVaultAPP#7]
Hi, there was some strange behaviour when editing a phone number on the app, Im happy to fix it if there is a way of running the app in dev mode?

**Comment by SimpleProgrammingAU** [comment]
Hi there,

Can you describe the issue? It may be a deliberate frustration to prevent users from entering an invalid phone number.

**Comment by MurrayJack** [comment]
Hi, yes, so

after entering a phone number that you notice you have typed it wrong (at say the beginning).  As you delete and change the number the cursor is reset to the end of the number in the control, so after every change you need to move this cursor to the correct place again. 

While i'm thinking about it, if you require +61 just add it in code, detect its not there and just add on save, rather that try to add it to the text box

**Comment by SimpleProgrammingAU** [comment]
Interesting. I cannot replicate this issue on my own device. When I delete and change a number anywhere in the text box, my cursor stays where it would be expected.

Which device, OS and browser (+ version information) are you using?

Given this platform is superseded by state-based offerings, I don't intend to make additional updates beyond bugfixes as I believe a central solution is better than disparate options like mine and the many others available on the market. (That is not to say I endorse how Victoria has implemented their centralised contact registration solution.)

**Comment by MurrayJack** [comment]
im on a iphone 12 pro , all the latest ios updates

**Comment by SimpleProgrammingAU** [comment]
That's not enough information.

Can you provide version numbers of iOS and Safari?

**Comment by SimpleProgrammingAU** [comment]
Closed due to inactivity during triage.
